name: CI and automatic releases
on:
  push:
    branches-ignore: [gh-pages]
jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test LTS releases
        java: [8, 11]
    name: "java${{ matrix.java }}-${{ matrix.os }}" # Do not change; used by protected branches
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --scan
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestCoverageVerification
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports
          path: build/reports/

  release:
    needs: ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Node.js dependencies
        run: npm install

      - name: Generate docs
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: dokkaHtml
      # Ridiculous workaround for https://github.com/Kotlin/dokka/issues/163
      - name: Move Dokka's assets into a sensible place
        run: |
          set -x -o nounset -o errexit -o pipefail
          cd ./build/dokka/html
          mv ./styles ./images ./scripts navigation.html ./cogrpc/
          find ./cogrpc/ -name '*.html' -print0 | xargs -0 sed -i 's;../styles/;styles/;g'
          find ./cogrpc/ -name '*.html' -print0 | xargs -0 sed -i 's;../images/;images/;g'
          find ./cogrpc/ -name '*.html' -print0 | xargs -0 sed -i 's;../scripts/;scripts/;g'
          find ./cogrpc/ -name '*.html' -print0 | xargs -0 sed -i 's;pathToRoot = "../;pathToRoot = ";g'
          sed -i 's;href="cogrpc/;href=";g' ./cogrpc/navigation.html

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_PASSPHRASE }}

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_branch: gh-pages
          publish_dir: ./build/dokka/html/cogrpc
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
